name = "ordini-lampo-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "db17f1e14132406da866dc449866cd9c"

[[queues.producers]]
queue = "ordini-lampo-outbox"
binding = "OUTBOX_QUEUE"

[vars]
ENVIRONMENT = "production"
LOG_LEVEL = "info"
API_VERSION = "1.2.0-slots"
